name       : mgard
version    : 1.0.0
release    : 1
source     :
    - https://github.com/CODARcode/MGARD/archive/refs/tags/1.0.0.tar.gz : 2dd153abc9bef7d87923cdefca6243b2050b7522e1d2b196e04c73c5cee6e880
homepage   : https://github.com/CODARcode/MGARD
license    : Apache-2.0
component  : programming.library
summary    : MultiGrid Adaptive Reduction of Data
description: |
    MGARD (MultiGrid Adaptive Reduction of Data) is a technique for multilevel lossy compression of scientific data based on the theory of multigrid methods.
builddeps  :
    - pkgconfig(libzstd)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/include/mgard/MGARDConfig.h.in
